run:
  timeout: 5m
  go: "1.23"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - gosec

linters-settings:
  gosec:
    excludes:
      - G104
      - G304
      - G404
  revive:
    rules:
      - name: var-naming
      - name: exported
      - name: unexported-return
      - name: unused-parameter
        disabled: true

issues:
  exclude-dirs:
    - internal/api/web_dist
    - terraform-provider-selfcloud
  max-issues-per-linter: 0
  max-same-issues: 0
